# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#

<% require 'socket'
   host = Socket.gethostname
%>

<% %w(development test production).each do |env| %>
<%= env %>:
  piwik:
    id_site: 3
    url: <%= host %>.icd.teradyne.com/analytics
    use_async: false
    disabled: false
<% end %>

