require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuantitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Quantity. As you add validations to Quantity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.build(:quantity).attributes
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuantitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all quantities as @quantities" do
      quantity = Quantity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quantities).should eq([quantity])
    end
  end

  describe "GET show" do
    it "assigns the requested quantity as @quantity" do
      quantity = Quantity.create! valid_attributes
      get :show, {:id => quantity.to_param}, valid_session
      assigns(:quantity).should eq(quantity)
    end
  end

  describe "GET new" do
    it "assigns a new quantity as @quantity" do
      get :new, {}, valid_session
      assigns(:quantity).should be_a_new(Quantity)
    end
  end

  describe "GET edit" do
    it "assigns the requested quantity as @quantity" do
      quantity = Quantity.create! valid_attributes
      get :edit, {:id => quantity.to_param}, valid_session
      assigns(:quantity).should eq(quantity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Quantity" do
        expect {
          post :create, {:quantity => valid_attributes}, valid_session
        }.to change(Quantity, :count).by(1)
      end

      it "assigns a newly created quantity as @quantity" do
        post :create, {:quantity => valid_attributes}, valid_session
        assigns(:quantity).should be_a(Quantity)
        assigns(:quantity).should be_persisted
      end

      it "redirects to the created quantity" do
        post :create, {:quantity => valid_attributes}, valid_session
        response.should redirect_to(Quantity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quantity as @quantity" do
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Quantity) do |u|
          stub(u).valid? {false}
        end
        #Quantity.any_instance.stub(:save).and_return(false)
        post :create, {:quantity => {  }}, valid_session
        assigns(:quantity).should be_a_new(Quantity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Quantity) do |u|
          stub(u).valid? {false}
        end
        #Quantity.any_instance.stub(:save).and_return(false)
        post :create, {:quantity => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quantity" do
        quantity = Quantity.create! valid_attributes
        # Assuming there are no other quantities in the database, this
        # specifies that the Quantity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        any_instance_of(Quantity) do |u|
          mock(u).update_attributes({'these' => 'params'})
        end
        #Quantity.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => quantity.to_param, :quantity => { "these" => "params" }}, valid_session
      end

      it "assigns the requested quantity as @quantity" do
        quantity = Quantity.create! valid_attributes
        put :update, {:id => quantity.to_param, :quantity => valid_attributes}, valid_session
        assigns(:quantity).should eq(quantity)
      end

      it "redirects to the quantity" do
        quantity = Quantity.create! valid_attributes
        put :update, {:id => quantity.to_param, :quantity => valid_attributes}, valid_session
        response.should redirect_to(quantity)
      end
    end

    describe "with invalid params" do
      it "assigns the quantity as @quantity" do
        quantity = Quantity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Quantity) do |u|
          stub(u).valid? {false}
        end
        #Quantity.any_instance.stub(:save).and_return(false)
        put :update, {:id => quantity.to_param, :quantity => {  }}, valid_session
        assigns(:quantity).should eq(quantity)
      end

      it "re-renders the 'edit' template" do
        quantity = Quantity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Quantity) do |u|
          stub(u).valid? {false}
        end
        #Quantity.any_instance.stub(:save).and_return(false)
        put :update, {:id => quantity.to_param, :quantity => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quantity" do
      quantity = Quantity.create! valid_attributes
      expect {
        delete :destroy, {:id => quantity.to_param}, valid_session
      }.to change(Quantity, :count).by(-1)
    end

    it "redirects to the quantities list" do
      quantity = Quantity.create! valid_attributes
      delete :destroy, {:id => quantity.to_param}, valid_session
      response.should redirect_to(quantities_url)
    end
  end

end
