require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SizesController do

  # This should return the minimal set of attributes required to create a valid
  # Size. As you add validations to Size, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.build(:size).attributes
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SizesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sizes as @sizes" do
      size = Size.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sizes).should eq([size])
    end
  end

  describe "GET show" do
    it "assigns the requested size as @size" do
      size = Size.create! valid_attributes
      get :show, {:id => size.to_param}, valid_session
      assigns(:size).should eq(size)
    end
  end

  describe "GET new" do
    it "assigns a new size as @size" do
      get :new, {}, valid_session
      assigns(:size).should be_a_new(Size)
    end
  end

  describe "GET edit" do
    it "assigns the requested size as @size" do
      size = Size.create! valid_attributes
      get :edit, {:id => size.to_param}, valid_session
      assigns(:size).should eq(size)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Size" do
        expect {
          post :create, {:size => valid_attributes}, valid_session
        }.to change(Size, :count).by(1)
      end

      it "assigns a newly created size as @size" do
        post :create, {:size => valid_attributes}, valid_session
        assigns(:size).should be_a(Size)
        assigns(:size).should be_persisted
      end

      it "redirects to the created size" do
        post :create, {:size => valid_attributes}, valid_session
        response.should redirect_to(Size.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved size as @size" do
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Size) do |u|
          stub(u).valid? {false}
        end
        #Size.any_instance.stub(:save).and_return(false)
        post :create, {:size => {  }}, valid_session
        assigns(:size).should be_a_new(Size)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Size) do |u|
          stub(u).valid? {false}
        end
        #Size.any_instance.stub(:save).and_return(false)
        post :create, {:size => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested size" do
        size = Size.create! valid_attributes
        # Assuming there are no other sizes in the database, this
        # specifies that the Size created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        any_instance_of(Size) do |u|
          mock(u).update_attributes({'these' => 'params'})
        end
        #Size.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => size.to_param, :size => { "these" => "params" }}, valid_session
      end

      it "assigns the requested size as @size" do
        size = Size.create! valid_attributes
        put :update, {:id => size.to_param, :size => valid_attributes}, valid_session
        assigns(:size).should eq(size)
      end

      it "redirects to the size" do
        size = Size.create! valid_attributes
        put :update, {:id => size.to_param, :size => valid_attributes}, valid_session
        response.should redirect_to(size)
      end
    end

    describe "with invalid params" do
      it "assigns the size as @size" do
        size = Size.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Size) do |u|
          stub(u).valid? {false}
        end
        #Size.any_instance.stub(:save).and_return(false)
        put :update, {:id => size.to_param, :size => {  }}, valid_session
        assigns(:size).should eq(size)
      end

      it "re-renders the 'edit' template" do
        size = Size.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        any_instance_of(Size) do |u|
          stub(u).valid? {false}
        end
        #Size.any_instance.stub(:save).and_return(false)
        put :update, {:id => size.to_param, :size => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested size" do
      size = Size.create! valid_attributes
      expect {
        delete :destroy, {:id => size.to_param}, valid_session
      }.to change(Size, :count).by(-1)
    end

    it "redirects to the sizes list" do
      size = Size.create! valid_attributes
      delete :destroy, {:id => size.to_param}, valid_session
      response.should redirect_to(sizes_url)
    end
  end

end
